
name: Docker Image CI

on:
  workflow_dispatch:
  repository_dispatch:
    types: build_docker_image

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build docker and push to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/ubuntu/Dockerfile
          push: true
          tags: |
            wfrest/wfrest 
